// ./src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import "@/styles/theme.css";
import "@/styles/typography.css";
import "@/styles/structure.css";

import { AppProvider } from "@/providers/app-provider";
import { getUiRuntimeConfig } from "@/lib/ui/utils/getUiRuntimeConfig";
import { CMSProvider } from "@/providers/cms-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontFamily = `${geistSans.variable} ${geistMono.variable}`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Get the UI runtime contract for AppProvider
  const uiRuntimeConfig = await getUiRuntimeConfig();

  let className = "antialiased";
  className += " min-h-screen";
  className += " overflow-hidden";
  // className += " border-2 border-purple-500";
  // className += " p-2";
  className += " max-h-screen";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontFamily} ${className}`}
      >
        <AppProvider uiRuntimeConfig={uiRuntimeConfig}>
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CMSProvider>
              {children}
            </CMSProvider>
          </NextThemesProvider>
        </AppProvider>
      </body>
    </html>
  );
}
