services:
  cms:
    container_name: ${COMPOSE_PROJECT_NAME}_cms
    build:
      context: .
      dockerfile: Dockerfile.local
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      # DATABASE_HOST: db
      # DATABASE_NAME: strapi
      # DATABASE_USERNAME: strapi_admin
      # DATABASE_PASSWORD: password
      # DATABASE_PORT: ${DATABASE_PORT}
      APP_KEYS: ${APP_KEYS}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}

      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads
      - ./config:/opt/app/config
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.tmp:/opt/app/.tmp

      - ./.env:/opt/app/.env
    ports:
      - '1337:1337'
    # networks:
    #   - cms
      
  # db:
  #   container_name: ${COMPOSE_PROJECT_NAME}_db
  #   # platform: linux/amd64 #for platform error on Apple M1 chips
  #   restart: unless-stopped
  #   env_file: .env
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   volumes:
  #     - db_data:/var/lib/postgresql/data/ #using a volume
  #     #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - cms
      
  # adminer:
  #   container_name: ${COMPOSE_PROJECT_NAME}_adminer
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '9090:8080'
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=db
  #   networks:
  #     - cms
  #   depends_on:
  #     - db

# networks:
#   cms:
#     name: ${COMPOSE_PROJECT_NAME}_cms
#     driver: bridge
